#!/usr/bin/env python3
"""Genereaza memoria permanenta a proiectului (harta codului + harta API).

Output:
  docs/memory/CODE_MAP.md  - sectiuni + functii top-level din JS si Python
  docs/memory/API_MAP.md   - toate rutele Flask (blueprints + app.py)

Ruleaza dupa orice modificare structurala (functii/rute noi):
  python scripts/gen_memory.py

Fara dependente externe, fara timestamp (regenerarea identica = diff zero).
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / 'docs' / 'memory'

JS_FILES = [
    'static/app.js',
    'static/mobile.js',
    'static/core.js',
    'static/budget/budget-tracker.js',
]
PY_FILES = ['app.py', 'database.py', 'utils.py', 'csrf.py', 'labels.py']

AUTOGEN_NOTE = ('<!-- AUTO-GENERATED by scripts/gen_memory.py - do not edit by hand. '
                'Regenerate after structural changes. -->')

SECTION_RE = re.compile(r'^//\s*={4,}\s*(.+?)\s*={4,}\s*/*\s*$')
JS_FUNC_RES = [
    re.compile(r'^(?:async\s+)?function\s+(\w+)\s*\('),
    re.compile(r'^(?:const|let|var)\s+(\w+)\s*=\s*(?:async\s*)?(?:function\b|\([^)]*\)\s*=>|\w+\s*=>)'),
    re.compile(r'^window\.(\w+)\s*=\s*(?:async\s*)?function\b'),
]
PY_DEF_RE = re.compile(r'^(?:def|class)\s+(\w+)')
ROUTE_RE = re.compile(r"^@(\w+)\.route\(\s*['\"]([^'\"]+)['\"](.*)$")
METHODS_RE = re.compile(r"methods\s*=\s*\[([^\]]*)\]")
DEF_AFTER_RE = re.compile(r'^def\s+(\w+)')


def parse_js(path: Path):
    """Returneaza [(sectiune, [(linie, nume_functie), ...]), ...]."""
    sections = []
    current = ('(top)', [])
    for i, line in enumerate(path.read_text(encoding='utf-8').splitlines(), 1):
        m = SECTION_RE.match(line)
        if m:
            if current[1] or current[0] != '(top)':
                sections.append(current)
            current = (m.group(1), [])
            continue
        for rx in JS_FUNC_RES:
            fm = rx.match(line)
            if fm:
                current[1].append((i, fm.group(1)))
                break
    sections.append(current)
    return sections


def parse_py_defs(path: Path):
    out = []
    for i, line in enumerate(path.read_text(encoding='utf-8').splitlines(), 1):
        m = PY_DEF_RE.match(line)
        if m:
            out.append((i, m.group(1)))
    return out


def parse_routes(path: Path):
    """Returneaza [(linie, metode, rule, functie), ...]."""
    lines = path.read_text(encoding='utf-8').splitlines()
    routes = []
    for i, line in enumerate(lines):
        m = ROUTE_RE.match(line.strip())
        if not m:
            continue
        rule, rest = m.group(2), m.group(3)
        mm = METHODS_RE.search(rest)
        methods = (','.join(s.strip().strip("'\"") for s in mm.group(1).split(','))
                   if mm else 'GET')
        func = '?'
        for j in range(i + 1, min(i + 8, len(lines))):
            dm = DEF_AFTER_RE.match(lines[j].strip())
            if dm:
                func = dm.group(1)
                break
        routes.append((i + 1, methods, rule, func))
    return routes


def gen_code_map():
    out = ['# CODE MAP - PIF Dashboard', '', AUTOGEN_NOTE, '',
           'Harta sectiunilor si functiilor top-level. Format: `linie: functie`.', '']
    for rel in JS_FILES:
        path = ROOT / rel
        if not path.exists():
            continue
        total = sum(1 for _ in path.open(encoding='utf-8'))
        out += [f'## {rel} ({total} linii)', '']
        for section, funcs in parse_js(path):
            if not funcs:
                continue
            out.append(f'### {section}')
            out.append('')
            out.append(', '.join(f'`{ln}:{fn}`' for ln, fn in funcs))
            out.append('')
    for rel in PY_FILES:
        path = ROOT / rel
        if not path.exists():
            continue
        total = sum(1 for _ in path.open(encoding='utf-8'))
        out += [f'## {rel} ({total} linii)', '']
        defs = parse_py_defs(path)
        out.append(', '.join(f'`{ln}:{fn}`' for ln, fn in defs) if defs else '_(fara definitii top-level)_')
        out.append('')
    return '\n'.join(out) + '\n'


def gen_api_map():
    out = ['# API MAP - PIF Dashboard', '', AUTOGEN_NOTE, '',
           'Toate rutele Flask. Pentru schema DB vezi SCHEMA_REFERENCE.md.', '']
    total = 0
    files = sorted((ROOT / 'blueprints').glob('*.py')) + [ROOT / 'app.py']
    for path in files:
        routes = parse_routes(path)
        if not routes:
            continue
        total += len(routes)
        rel = path.relative_to(ROOT)
        out += [f'## {rel} ({len(routes)} rute)', '',
                '| Metode | Path | Functie | Linie |', '|---|---|---|---|']
        for ln, methods, rule, func in routes:
            out.append(f'| {methods} | `{rule}` | `{func}` | {ln} |')
        out.append('')
    out.insert(5, f'**Total: {total} rute.**')
    out.insert(6, '')
    return '\n'.join(out) + '\n'


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    code_map = gen_code_map()
    api_map = gen_api_map()
    (OUT_DIR / 'CODE_MAP.md').write_text(code_map, encoding='utf-8')
    (OUT_DIR / 'API_MAP.md').write_text(api_map, encoding='utf-8')
    print(f'OK: {OUT_DIR / "CODE_MAP.md"} ({len(code_map.splitlines())} linii)')
    print(f'OK: {OUT_DIR / "API_MAP.md"} ({len(api_map.splitlines())} linii)')


if __name__ == '__main__':
    main()
