#!/usr/bin/env python3
"""Genereaza memoria permanenta a proiectului (harta codului + harta API).

Output:
  docs/memory/CODE_MAP.md  - sectiuni + functii top-level din JS si Python
  docs/memory/API_MAP.md   - toate rutele Flask (blueprints + app.py)
  docs/memory/DB_MAP.md    - schema reala (PRAGMA pe o baza construita pe loc)

Ruleaza dupa orice modificare structurala (functii/rute noi):
  python scripts/gen_memory.py

Fara dependente externe, fara timestamp (regenerarea identica = diff zero).
"""

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / 'docs' / 'memory'

# `static/{app,mobile,core}.js` au fost sterse odata cu aplicatia legacy (2026-06-17).
# Singurul JS ramas in static/ e service-worker.js; restul e Svelte, compilat in dist.
JS_FILES = [
    'static/service-worker.js',
]
# Lista era scrisa de mana si sarea peste TOATE blueprint-urile (~3.900 de linii,
# adica exact suprafata de API). Hook-ul de pre-commit se declansa pe
# `blueprints/*.py` si regenera o harta care structural nu putea contine ce se
# schimbase. Acum radacina se scaneaza singura, deci un modul nou intra fara sa-si
# aminteasca cineva sa-l adauge aici.
PY_FILES = (['app.py', 'database.py', 'utils.py', 'csrf.py', 'labels.py']
            + sorted('blueprints/%s' % p.name
                     for p in (ROOT / 'blueprints').glob('*.py')
                     if p.name != '__init__.py'))

AUTOGEN_NOTE = ('<!-- AUTO-GENERATED by scripts/gen_memory.py - do not edit by hand. '
                'Regenerate after structural changes. -->')

SECTION_RE = re.compile(r'^//\s*={4,}\s*(.+?)\s*={4,}\s*/*\s*$')
JS_FUNC_RES = [
    re.compile(r'^(?:async\s+)?function\s+(\w+)\s*\('),
    re.compile(r'^(?:const|let|var)\s+(\w+)\s*=\s*(?:async\s*)?(?:function\b|\([^)]*\)\s*=>|\w+\s*=>)'),
    re.compile(r'^window\.(\w+)\s*=\s*(?:async\s*)?function\b'),
]
PY_DEF_RE = re.compile(r'^(?:def|class)\s+(\w+)')
ROUTE_RE = re.compile(r"^@(\w+)\.route\(\s*['\"]([^'\"]+)['\"](.*)$")
METHODS_RE = re.compile(r"methods\s*=\s*\[([^\]]*)\]")
DEF_AFTER_RE = re.compile(r'^def\s+(\w+)')


def parse_js(path: Path):
    """Returneaza [(sectiune, [(linie, nume_functie), ...]), ...]."""
    sections = []
    current = ('(top)', [])
    for i, line in enumerate(path.read_text(encoding='utf-8').splitlines(), 1):
        m = SECTION_RE.match(line)
        if m:
            if current[1] or current[0] != '(top)':
                sections.append(current)
            current = (m.group(1), [])
            continue
        for rx in JS_FUNC_RES:
            fm = rx.match(line)
            if fm:
                current[1].append((i, fm.group(1)))
                break
    sections.append(current)
    return sections


def parse_py_defs(path: Path):
    out = []
    for i, line in enumerate(path.read_text(encoding='utf-8').splitlines(), 1):
        m = PY_DEF_RE.match(line)
        if m:
            out.append((i, m.group(1)))
    return out


def parse_routes(path: Path):
    """Returneaza [(linie, metode, rule, functie), ...]."""
    lines = path.read_text(encoding='utf-8').splitlines()
    routes = []
    for i, line in enumerate(lines):
        m = ROUTE_RE.match(line.strip())
        if not m:
            continue
        rule, rest = m.group(2), m.group(3)
        mm = METHODS_RE.search(rest)
        methods = (','.join(s.strip().strip("'\"") for s in mm.group(1).split(','))
                   if mm else 'GET')
        func = '?'
        for j in range(i + 1, min(i + 8, len(lines))):
            dm = DEF_AFTER_RE.match(lines[j].strip())
            if dm:
                func = dm.group(1)
                break
        routes.append((i + 1, methods, rule, func))
    return routes


def gen_code_map():
    out = ['# CODE MAP - PIF Dashboard', '', AUTOGEN_NOTE, '',
           'Harta sectiunilor si functiilor top-level. Format: `linie: functie`.', '']
    for rel in JS_FILES:
        path = ROOT / rel
        if not path.exists():
            continue
        total = sum(1 for _ in path.open(encoding='utf-8'))
        out += [f'## {rel} ({total} linii)', '']
        for section, funcs in parse_js(path):
            if not funcs:
                continue
            out.append(f'### {section}')
            out.append('')
            out.append(', '.join(f'`{ln}:{fn}`' for ln, fn in funcs))
            out.append('')
    for rel in PY_FILES:
        path = ROOT / rel
        if not path.exists():
            continue
        total = sum(1 for _ in path.open(encoding='utf-8'))
        out += [f'## {rel} ({total} linii)', '']
        defs = parse_py_defs(path)
        out.append(', '.join(f'`{ln}:{fn}`' for ln, fn in defs) if defs else '_(fara definitii top-level)_')
        out.append('')
    return '\n'.join(out) + '\n'


def gen_api_map():
    out = ['# API MAP - PIF Dashboard', '', AUTOGEN_NOTE, '',
           'Toate rutele Flask. Pentru schema DB vezi `DB_MAP.md` (generat din baza).', '']
    total = 0
    files = sorted((ROOT / 'blueprints').glob('*.py')) + [ROOT / 'app.py']
    for path in files:
        routes = parse_routes(path)
        if not routes:
            continue
        total += len(routes)
        rel = path.relative_to(ROOT)
        out += [f'## {rel} ({len(routes)} rute)', '',
                '| Metode | Path | Functie | Linie |', '|---|---|---|---|']
        for ln, methods, rule, func in routes:
            out.append(f'| {methods} | `{rule}` | `{func}` | {ln} |')
        out.append('')
    out.insert(5, f'**Total: {total} rute.**')
    out.insert(6, '')
    return '\n'.join(out) + '\n'


LABEL_DICT_RE = re.compile(r'^(\w+_STATUS_LABELS)\s*=\s*\{(.*?)^\}', re.M | re.S)
LABEL_KEY_RE = re.compile(r"^\s*'([^']+)':", re.M)

# Codul care construieste o baza de unica folosinta si scoate schema ei ca JSON.
# Ruleaza in subproces fiindca `database.py` isi citeste calea din mediu la import.
SONDA = '''
import json, os, sqlite3, sys
sys.path.insert(0, sys.argv[1])
import database
database.init_db()
database.run_migrations()
c = sqlite3.connect(os.environ['PIF_DB_PATH'])
cur = c.cursor()
cur.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
out = {}
for (t,) in cur.fetchall():
    if t.startswith('sqlite_'):
        continue
    cur.execute('PRAGMA table_info("%s")' % t)
    out[t] = [(r[1], r[2], bool(r[3]), r[4], bool(r[5])) for r in cur.fetchall()]
cur.execute('SELECT version FROM schema_version')
print(json.dumps({'version': cur.fetchone()[0], 'tables': out}))
'''


def parse_schema():
    """Schema REALA: construim o baza goala si o citim cu PRAGMA.

    Nu parsam `init_db()` din sursa. Motivul e masurat: `init_db` creeaza
    `tasks` cu 8 coloane, dar migrarile o duc la 15, si `calcule` nici nu
    apare acolo (o adauga v37). O harta scoasa din init_db ar fi fost
    incompleta EXACT ca documentele pe care fisierul asta le inlocuieste.
    Baza sondei e temporara si se sterge; baza reala nu e atinsa niciodata.
    """
    import json
    import subprocess
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        env = dict(os.environ, PIF_DB_PATH=str(Path(tmp) / 'probe.db'))
        res = subprocess.run([sys.executable, '-c', SONDA, str(ROOT)],
                             capture_output=True, text=True, env=env, cwd=str(ROOT))
    if res.returncode != 0:
        raise SystemExit('gen_memory: sonda de schema a esuat:\n' + res.stderr[-2000:])
    data = json.loads(res.stdout.strip().splitlines()[-1])
    return data['version'], sorted(data['tables'].items())


def parse_labels():
    text = (ROOT / 'labels.py').read_text(encoding='utf-8')
    out = {}
    for m in LABEL_DICT_RE.finditer(text):
        out[m.group(1)] = LABEL_KEY_RE.findall(m.group(2))
    return out


def gen_db_map():
    version, tables = parse_schema()
    out = ['# DB MAP - PIF Dashboard', '', AUTOGEN_NOTE, '',
           f'**Schema v{version}, {len(tables)} tabele.** Citit cu PRAGMA dintr-o baza',
           'construita pe loc (init_db + toate migrarile), deci e schema pe care o are',
           'o instalare noua — nu ce zice o sectiune scrisa de mana.', '']
    for name, cols in tables:
        out += [f'## {name} ({len(cols)} coloane)', '']
        out.append('| coloana | tip | note |')
        out.append('|---|---|---|')
        for col, typ, notnull, default, pk in cols:
            note = ', '.join(f for f in (
                'PK' if pk else '',
                'NOT NULL' if notnull and not pk else '',
                f'default {default}' if default not in (None, '') else '') if f)
            out.append(f'| `{col}` | {typ} | {note} |')
        out.append('')
    labels = parse_labels()
    if labels:
        out += ['## Valori de status (din `labels.py`)', '']
        for dict_name, keys in sorted(labels.items()):
            canon = [k for k in keys if k not in
                     ('in_lucru', 'in_asteptare', 'in_așteptare', 'blocat', 'finalizat')
                     or dict_name.startswith('PROJECT') and k == 'finalizat'
                     or dict_name.startswith('TASK') and k == 'done']
            out.append(f'- `{dict_name}` — scrise de aplicatie: '
                       + ', '.join(f'`{k}`' for k in canon))
            out.append(f'  (mai sunt mapate, doar la CITIRE, cheile vechi: '
                       + ', '.join(f'`{k}`' for k in keys if k not in canon) + ')')
        out.append('')
    return '\n'.join(out) + '\n'


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    code_map = gen_code_map()
    api_map = gen_api_map()
    db_map = gen_db_map()
    (OUT_DIR / 'CODE_MAP.md').write_text(code_map, encoding='utf-8')
    (OUT_DIR / 'API_MAP.md').write_text(api_map, encoding='utf-8')
    (OUT_DIR / 'DB_MAP.md').write_text(db_map, encoding='utf-8')
    print(f'OK: {OUT_DIR / "CODE_MAP.md"} ({len(code_map.splitlines())} linii)')
    print(f'OK: {OUT_DIR / "API_MAP.md"} ({len(api_map.splitlines())} linii)')
    print(f'OK: {OUT_DIR / "DB_MAP.md"} ({len(db_map.splitlines())} linii)')


if __name__ == '__main__':
    main()
